name: tests
on: [push]

permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: write

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # https://github.com/cypress-io/github-action
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          record: true
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      - name: Deploy Report to GitHub Pages 
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./projects/pjypo8/
          publish_branch: gh-pages
          force_orphan: true
